spring.application.name=PointOfSale

# =========================
# Database Configuration
# =========================
spring.datasource.url=jdbc:postgresql://localhost:5432/pointofsale
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# =========================
# JPA / Hibernate
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# =========================
# Flyway Migration (disabled)
# =========================
spring.flyway.enabled=false

# =========================
# Server Settings
# =========================
server.port=8080
